# pytest.ini
[pytest]
pythonpath = .
addopts = -v -s --alluredir=./allure-results
python_files = *_tests.py test_*.py   # Устанавливает правила для тестовых файлов
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций
markers =
    users: Маркировка для тестов, связанных с пользователями.
    regression: Маркировка для регрессионных тестов.
    authentication: Маркировка для тестов аутентификации.
    files: Маркировка для тестов, связанных с файлами.
    courses: Маркировка для тестов, связанных с курсами.
    exercises: Маркировка для тестов, связанных с заданиями.